<?php
// Variables
return [
  "creatorName" => "ThemeSelection",
  "creatorUrl" => "https://themeselection.com",
  "templateName" => "Sneat",
  "templateSuffix" => "Laravel Bootstrap Starter Kit",
  "templateVersion" => "1.0.0",
  "templateFree" => true,
  "templateDescription" => "Laravel 12 Starter Kit with Bootstrap 5 – Powerful template for developers, offering clean code and seamless integration with Bootstrap 5 components.",
  "templateKeyword" => "laravel 12 starter kit, laravel bootstrap 5, bootstrap 5 starter kit, laravel bootstrap template, developer-friendly dashboard template",
  "licenseUrl" => "https://themeselection.com/license/",
  "livePreview" => "https://demos.themeselection.com/sneat-bootstrap-html-laravel-admin-template-free/demo/",
  "productPage" => "https://themeselection.com/item/sneat-dashboard-free-laravel/",
  "ogTitle" => "Laravel Bootstrap Starter Kit by ThemeSelection",
  "ogType" => "product",
  "ogImage" => "https://ts-assets.b-cdn.net/ts-assets/sneat/sneat-bootstrap-laravel-admin-template-free/banner/banner-light.png",
  "support" => "https://github.com/themeselection/sneat-html-laravel-admin-template-free/issues",
  "moreThemes" => "https://themeselection.com/",
  "documentation" => "https://demos.themeselection.com/sneat-bootstrap-html-admin-template/documentation",
  "repository" => "https://github.com/themeselection/sneat-bootstrap-html-laravel-admin-template-free",
  "gitRepo" => "https://github.com/themeselection/sneat-bootstrap-html-laravel-admin-template-free.git",
  "gitRepoAccess" => "https://tools.themeselection.com/github/github-access",
  "githubFreeUrl" => "https://github.com/themeselection",
  "facebookUrl" => "https://www.facebook.com/ThemeSelections/",
  "twitterUrl" => "https://twitter.com/Theme_Selection",
  "githubUrl" => "https://github.com/themeselection",
  "dribbbleUrl" => "https://dribbble.com/themeselection",
  "instagramUrl" => "https://www.instagram.com/themeselection/"
];
