name: Linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, bcmath, intl

      - name: Add Composer credentials from ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install PHP dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Node.js and Install NPM dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - run: npm install

      - name: Run Pint for PHP code style checks
        run: vendor/bin/pint

      - name: Run ESLint for JavaScript/TypeScript
        run: npx eslint . --ext .js,.ts --max-warnings 0

      - name: Run Stylelint for CSS/SCSS (if applicable)
        run: npx stylelint "**/*.scss" "**/*.css" --max-warnings 0

      # Optionally, commit any changes to code style (uncomment if needed)
      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'
      #     file_pattern: '**/*'
